### PR TITLE
Ticket Reference handling #1048

### PR DESCRIPTION
**Pull request by paulsputer**
+ Supports referencing:
  + from other tickets via comments
  + from commits on other branches

### CODE REVIEW

**Comment by paulsputer** [comment]
### Example showing reference by commit `8E5DA2` and `ticket/2`
ticketreferences

**Comment by paulsputer** [comment]
@gitblit could you cast an eye over this and share your thoughts?

**Comment by gitblit** [comment]
I will cast my eye.  Trying to make time.

**Comment by gitblit** [comment]
Thoughts...

1. We need to unit test the new features of TicketModel and ITicketService.
2. I think the use of lozenges for commit links and ticket links overloads their appearance value.  I would advocate it would be better to use a plain, fixed-width font link for commit shas and a plain link for the ticket reference.

**Comment by paulsputer** [comment]
Thanks James, (1) will do, (2) very true, I tried to use the lowest level lozenge but still looks a bit too much, I'll make those fixes and post back.

**Comment by paulsputer** [comment]
ok @gitblit can you take another look at this and see if there's anything else we need to address on referencing in this PR? It's getting a bit larger than I was anticipating, then again half of it is testing the different use cases.

**Comment by paulsputer** [comment]
Here's the updated UI
gitblitrefui2

**Pull request merged**
