### PR TITLE
Adding Kerberos5/GSS authentication to ssh

### PR DESCRIPTION
**Pull request by fbacchella**
Adding the possibility to define authentication method order for ssh

### CODE REVIEW

**Comment by gitblit** [comment]
Hi Fabrice,

This will need to be rebased against `develop` and we'll need some unit tests to ensure your changes work and don't break anything else.

-J

**Comment by fbacchella** [comment]
I tried to have a look about tests. But I didn't get it. What class should I look at to start a test ssh server and test it results ?

**Comment by gitblit** [comment]
This is a good place to start:
https://github.com/gitblit/gitblit/blob/develop/src/test/java/com/gitblit/tests/SshDaemonTest.java#L45

The server will automatically be started for you.

**Comment by fbacchella** [comment]
It's done in pull request #254

**Pull request closed without merging**
