### PR TITLE
Secure cookies

### PR DESCRIPTION
**Pull request by fzs**
Gitblit already set the "secure" flag for cookies, i.e. send them only over secured transports, as well as 'httpOnly' flag for the Jetty session cookies already.
With this PR it will also do so for the user authentication cookies.

It will also set the 'secure' flag when HTTP is redirected to HTTPS by Gitblit.

### CODE REVIEW

**Comment by gitblit** [comment]
:+1:

**Comment by tomposmiko** [comment]
It fails to compile:

```
compile:
  [mx:keys] =========================================================
  [mx:keys] mx:Keys  (com.gitblit.Keys)
  [mx:keys] ---------------------------------------------------------
  [mx:keys]    input: /data/src/gitblit/src/main/distrib/data/defaults.properties
  [mx:keys]    output: /data/src/gitblit/src/main/java/com/gitblit/Keys.java
 [mx:javac] =========================================================
 [mx:javac] mx:Javac  (com.gitblit:gitblit:1.8.1-SNAPSHOT, compile)
 [mx:javac] ---------------------------------------------------------
 [mx:javac] Cleaning apt source directory src/main/gen
 [mx:javac] Cleaning output directory /data/src/gitblit/build/classes
 [mx:javac] Compiling 457 source files to /data/src/gitblit/build/classes
 [mx:javac] /data/src/gitblit/src/main/java/com/gitblit/models/UserModel.java:40: error: a type with the same simple name is already defined by the single-type-import of SecureRandom
 [mx:javac] import com.gitblit.utils.SecureRandom;
 [mx:javac] ^
 [mx:javac] /data/src/gitblit/src/main/java/com/gitblit/models/UserModel.java:669: error: cannot find symbol
 [mx:javac] 		return StringUtils.getSHA1(RANDOM.randomBytes(32));
 [mx:javac] 		                                 ^
 [mx:javac]   symbol:   method randomBytes(int)
 [mx:javac]   location: variable RANDOM of type SecureRandom
 [mx:javac] Note: Some input files use or override a deprecated API.
 [mx:javac] Note: Recompile with -Xlint:deprecation for details.
 [mx:javac] Note: Some input files use unchecked or unsafe operations.
 [mx:javac] Note: Recompile with -Xlint:unchecked for details.
 [mx:javac] 2 errors

BUILD FAILED
/data/src/gitblit/build.xml:110: Compile failed; see the compiler error output for details.
```

**Comment by gitblit** [comment]
Hey Tamas, the compile problem is not related to this PR. It does look like we'll need to review the class name and import collision on the SecureRandom class recently introduced.

**Comment by tomposmiko** [comment]
Do you want me to submit a separate issue?

**Comment by gitblit** [comment]
@tomposmiko Good idea.

**Comment by fzs** [comment]
@tomposmiko, don't bother, it is a quick fix. Already pushed to master.

**Comment by tomposmiko** [comment]
Thanks, I didn't have time until now:)

**Pull request merged**
