### PR TITLE
New rpc endpoint for listing all branches from a given repository

### PR DESCRIPTION
**Pull request by mystygage**
fix issue #1184

### CODE REVIEW

**Comment by gitblit** [comment]
See the note [here](https://github.com/mystygage/gitblit/blob/c4a9e435e34ef7e9bd2ac5c71a96855502091579/src/main/java/com/gitblit/Constants.java#L410-L411).

What if we instead added support to the existing `LIST_BRANCHES` call for a single repo?

**Comment by mystygage** [comment]
> What if we instead added support to the existing `LIST_BRANCHES` call for a single repo?

Ok, I'll rewrite my code.

**Comment by gitblit** [comment]
No, leave it.  You've moved the constant, that solves the immediate 
problem.

**Comment by gitblit** [comment]
I merged and then reverted.  We'll need a new PR to get this in.  We forgot to enforce access controls on the repo.

**Comment by mystygage** [comment]
Ok. So modifying `LIST_BRANCHES` with existing access control seems like the best solution

**Comment by fzs** [comment]
New PR is #1192

**Pull request merged**
