### PR TITLE
Added possibility to use secure hashes to store passwords

### PR DESCRIPTION
**Pull request by pingunaut**
Addresses #1166

PBKDF2WithHmacSHA256 is used instead of MD5.
https://www.owasp.org/index.php/Hashing_Java was used as a reference for the implementation

### CODE REVIEW

**Comment by fzs** [comment]
With which setup did you test this? OS, Java vendor and version?

**Comment by pingunaut** [comment]
Linux (Fedora), openjdk-8
I am able to test against Windows7, Oracle JRE 7 later this day

**Comment by fzs** [comment]
Okay, thanks.
I have started to integrate your changes, but will have/want to rewrite
them some.

**Comment by pingunaut** [comment]
Not as soon as I thought, but finally verified: Windows 7/Oracle JRE 7 is woking fine

**Pull request merged**
