### PR TITLE
Add support for NetBeans project

### PR DESCRIPTION
**Pull request by jeyoung**
I have added some support files for the project to load in NetBeans. This should allow more people to get started quickly with contributing to the project.

### CODE REVIEW

**Comment by gitblit** [comment]
@jeyoung  It'll be up to you to maintain this project file when dependencies change.

**Comment by jeyoung** [comment]
@gitblit This is fine. I'll leave this branch open for future updates.

**Comment by jeyoung** [comment]
Looks fairly easy to add NetBeans support to moxie. I'll attempt that.

**Comment by gitblit** [comment]
That would be the best approach for maintainability.

**Pull request merged**
