### PR TITLE
Updated Dependencies

### PR DESCRIPTION
**Pull request by wangliyu**
Groovy 2.4.3
JGit 4.0.0.201506090130-r
SLF4j 1.7.12
Wicket 1.4.23

### CODE REVIEW

**Comment by wangliyu** [comment]
As part of Eclipse mars release, the JGit is released 4.0, there is a big change:
https://dev.gitblit.com/commit/mirrors!jgit.git/686124bec32fcdee1545e7d9c312dcf0276b44af
 that cause gitblit compile error, also Groovy has updated to 2.4.3, Wicket 1.4.23, SLF4j 1.7.12, Please review and merge it in, also Since JGit 4.0, most of the class implemented AutoClosable interfaces, which means we can use try-with-resources feature from Java7. maybe need more tweak.

**Comment by gitblit** [comment]
I don't know that I am ready for JGit 4.0 yet.  Maybe.

**Comment by wangliyu** [comment]
I'll run the new change in my env for couple days see how it goes, I'm using GO version - with Java8.

**Comment by wangliyu** [comment]
here is the highlight of changes in 4.0:
https://wiki.eclipse.org/JGit/New_and_Noteworthy/4.0

**Comment by wangliyu** [comment]
I run the new build in my env, it works fine. clone/push/create branch/tag all are fine.

**Comment by gitblit** [comment]
I want to sit on updating to JGit 4.0.  I know there is at least one intermittent [bug] in it that would affect my normal usage workflow.  As for Guice 4.0, you may or may not have noticed that Gitblit uses  a [patched build of guice-servlet](https://github.com/gitblit/google-guice).  In order to safely update to Guice 4.0 we'd need to apply that patch to the 4.0 code base.

The other dependency update proposals are fine.

cc @gzsombor

[bug]: https://bugs.eclipse.org/bugs/show_bug.cgi?id=422988

**Comment by gitblit** [comment]
@wangliyu Please submit a new PR against `develop` without JGit 4 and without Guice 4.

**Pull request closed without merging**
