### PR TITLE
Added better logging for fail2ban

### PR DESCRIPTION
**Pull request by Enrico204**
Hi,

I've modified the logging on SSH User-Password authentication to log IP addresses. It can be useful in software as fail2ban :-)

### CODE REVIEW

**Comment by gitblit** [comment]
Looks good.  Would you move your document to src/site and maybe add a link to the fail2ban project?

**Comment by Enrico204** [comment]
Done ;-)

**Comment by gitblit** [comment]
Doh!  I missed that you are targeting master.  I'm only merging into develop.  Care to rebase and submit a new PR?  Sorry for the inconvenience.

**Comment by Enrico204** [comment]
no problem, I'll rebase my repo and create a new PR ;-)

**Pull request closed without merging**
