### PR TITLE
Add support nested groups on the Repositories page

### PR DESCRIPTION
**Pull request by pingunaut**
Fix for #725.

This includes #1224 from @ybosy, because a lot of the code of it was reusable.

Also covers  #527 

image

(Panel contains a lot of copy-paste code from RepositoriesPanel :( But this way I was able to keep the original RepositoriesPanel without changing it a lot. ...this could be done a lot easier after a wicket upgrade in my opinion ;))

### CODE REVIEW

**Comment by YandexWillKillYou** [comment]
Just got a task to realize similar functionality. Nice to see it done!

**Comment by fzs** [comment]
What would you think about listing repositories first?

Screenshot 2019-06-15 at 16 36 32

Leaving out the "guard rails" would look cleaner, but with many folders it might get difficult to see what group a repository belongs to. On the other hand, this is the opposite sorting to what one is used from a file explorer.

**Comment by pingunaut** [comment]
I like your approach a lot. looks much better in my opinion :+1:

**Comment by fzs** [comment]
Closed by a squash merge to master in commit 0bace7e

**Pull request closed without merging**
