### PR TITLE
Fix for #976 - Filestore links via browser

### PR DESCRIPTION
**Pull request by paulsputer**
+ GitLFS client support
+ FilestoreModel now parses meta file
+ Read meta heading from cache if available
+ Authentication based on accept headers for browser view filestore login
+ PathModel & PathChangeModel now understands filestore items
+ Zip & Rar downloads contain include filestore items
+ Filestore servlet returns LFS JSON error only if accepted by client
+ DiffStat now knows repository to allow identification of filestore items
+ Filestore items identified and returned via view, raw & blob links on
blame, commitDiff, commit and Tree pages

### CODE REVIEW

**Comment by gitblit** [comment]
Hi Paul,

Sorry for massive delay.  I'll be delaying some more.  In the midst of a major deployment at work.  Might be next week before I get breathing room.

Happy New Year, BTW.

**Comment by paulsputer** [comment]
Hi James, thanks, no worries.  Hope it goes smoothly and you manage some vacation time.

Happy New Year :)

**Comment by gitblit** [comment]
Looks good.

**Comment by paulsputer** [comment]
thanks

**Pull request merged**
