### PR TITLE
fix for #967 filestore menu and help

### PR DESCRIPTION
**Pull request by paulsputer**
Adds menu for non-admin users and relocates configuration help to site pages as discussed in #967.

### CODE REVIEW

**Comment by gitblit** [comment]
If we filter blobs by view permissions then I'd re-enable the file store page for users. Till we do that this page will remain admin only.

**Comment by paulsputer** [comment]
Ok will do.

**Comment by paulsputer** [comment]
@gitblit  Turned out more straightforward than I was expecting :)

**Comment by gitblit** [comment]
Looks good.  Nicely done!

**Pull request merged**
