### PR TITLE
#1156

### PR DESCRIPTION
**Pull request by jvaleriano**
Is a minnor change but allow the Administrator see all groups that match with realm.ldap.groupAdminMemberPattern property.

### CODE REVIEW

**Comment by fzs** [comment]
This patch is hard to read because it includes lots of lines where the only change seems to be whitespace and indentation change.
From what I can see it looks like your patch will add Gitblit administrators to every LDAP group. Which would solve your problem in #1156, but it doesn't fix the root of your problem, I believe. Plus, it is not a good idea, because team membership should be defined in LDAP.

**Comment by jvaleriano** [comment]
My bad sorry for the identation.
the idea is made a cache only for the groups that Im going to use for the git. so I cant put the realm.ldap.synchronize in true. But I need that an administrator could use all the groups that match with a pattern like "git_*"

**Comment by fzs** [comment]
The PR, as it is, cannot be merged. It adds all admins to all groups. Plus, by default, it synchronizes all groups from LDAP, even if synchronization is off. It tries to tackle the problem of seeing all groups with synchronization being off with the wrong approach.
I understand our problem, but I believe there must be a better solution.

What do you use as value for `groupAdminMemberPattern` in your installation? Which groups from your AD do you want in Gitblit? Could these be grouped under a common OU?

**Comment by fzs** [comment]
I'm closing this pull request as it cannot be merged the way it is as discussed above.
While the problem is valid, this is not the solution. Further discussion of the problem to find a proper solution can be hold in #1156, if desired.

**Pull request closed without merging**
