### PR TITLE
974 in browser doc editor

### PR DESCRIPTION
**Pull request by paulsputer**
Document editor support for (#974) using ProseMirror to support wider range of use cases in the longer term compared to original PR (#1009) with SimpleMDE.  Markdown activated in this PR by default though other formats can be supported.  Code editor to be addressed in a later PR using CodeMirror. 

@gitblit I've added in merge/rebase capabilities with as minimal changes as possible. If merge fails it currently returns an error and the changes are lost which should be rare but could be rather frustrating.  What would you recommend for this?

### CODE REVIEW

**Comment by paladox** [comment]
+1 thanks. I haven't tested but thanks for working on a built in editor.

**Comment by paladox** [comment]
Does this support an option to disable the editor if gitblit acts as a mirror.

**Comment by paulsputer** [comment]
At the moment the logic prevents a user from making a commit if they don't have write permissions.  So that should gracefully handle the mirroring case. It would probably be more intuitive if it also disables the links to the edit page and the edit page itself in this case.

**Comment by paulsputer** [comment]
@gitblit would be great to get your feedback so we can merge in :)

**Comment by gitblit** [comment]
Sorry Paul. I'm quite negligent and I'm traveling this week so I doubt I'll
get to it before next week. I trust your judgement so if you are ready to
merge and it's holding up your progress then go ahead and merge.

**Comment by paulsputer** [comment]
No worries James, thanks.

**Comment by paladox** [comment]
@paulsputer thanks.

Also do you have a screenshot of what it looks like please.

**Comment by paulsputer** [comment]
Hi @paladox here we go, I'm sure they'll be improvements to the UI as it gets used more and other formats and features are added. :)

## Full screen editing mode
doceditortest-fullscreen

## Normal editing mode - with Heading 1 currently selected
doceditortest-activeh1

## Commit dialog with default commit message
doceditortest-commit

**Comment by paladox** [comment]
@paulsputer yes probably but it already looks good, Thanks for working on it. It now allows users that are out about like on a mobile or tablet to be able to work on commits so thanks for allowing users to do this.

**Pull request merged**
